In [1]:
# set up
import pandas as pd
from IPython.display import display

pd.set_option('display.max_rows', 20)
shooting_agencies = pd.read_csv('fatal-police-shootings-agencies.csv')
fatal_shooting = pd.read_csv('fatal-police-shootings-data.csv')

In [2]:
# shooting per state raw
shooting_per_state = fatal_shooting.groupby(['state', 'county']).agg(incident_count=('county', 'size')).reset_index()

In [3]:
# shooting per state order by
shooting_per_state_order_by = shooting_per_state.sort_values(by='incident_count', ascending=False)
display(shooting_per_state_order_by)

     state          county  incident_count
111     CA     Los Angeles             222
90      AZ        Maricopa             151
1159    TX          Harris              96
124     CA  San Bernardino              79
1125    TX           Bexar              64
...    ...             ...             ...
912     OH          Shelby               1
435     KS    Pottawatomie               1
434     KS            Ness               1
433     KS      Montgomery               1
1400    WY        Sheridan               1

[1401 rows x 3 columns]

In [5]:
# county with most shootings
max_row = shooting_per_state.loc[shooting_per_state['incident_count'].idxmax()]
display(max_row)

state                      CA
county            Los Angeles
incident_count            222
Name: 111, dtype: object

In [6]:
# nbr of shooting exceeding 150
high_shooting = shooting_per_state[shooting_per_state['incident_count'] > 150].sort_values(by='incident_count', ascending=False)
display(high_shooting)

    state       county  incident_count
111    CA  Los Angeles             222
90     AZ     Maricopa             151

In [4]:
full_data = pd.merge(
    shooting_per_state,
    shooting_agencies,
    left_on=['state'],
    right_on=['state'],
    how='left'
).sort_values(by='incident_count', ascending=False)
selected_data = full_data[['state', 'county', 'incident_count']]
display(selected_data)

       state       county  incident_count
12224     CA  Los Angeles             222
12173     CA  Los Angeles             222
12175     CA  Los Angeles             222
12176     CA  Los Angeles             222
12177     CA  Los Angeles             222
...      ...          ...             ...
75217     NC    Alexander               1
75216     NC    Alexander               1
75215     NC    Alexander               1
75214     NC    Alexander               1
162829    WY     Sheridan               1

[162830 rows x 3 columns]